const DEFAULT_TARGET_LANGUAGE = "tr";
const MAX_LINE_LENGTH = 56;
const MAX_GROUP_CHARS = 170;
const TRACK_CUE_LOAD_ATTEMPTS = 5;
const TRACK_CUE_LOAD_INTERVAL_MS = 140;

let translatedVideoKey = null;
let translationInProgress = false;

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (!request || !request.type) {
    return;
  }

  if (request.type === "translateCurrentVideo") {
    const targetLanguage = request.targetLanguage || DEFAULT_TARGET_LANGUAGE;

    translateCurrentVideo(targetLanguage)
      .then((meta) => {
        sendResponse({ ok: true, meta });
      })
      .catch((error) => {
        sendResponse({ ok: false, error: error.message });
      });

    return true;
  }

  if (request.type === "getTranslationState") {
    sendResponse({ ok: true, applied: isTranslationAppliedForCurrentVideo(), inProgress: translationInProgress });
  }
});

async function translateCurrentVideo(targetLanguage) {
  const sourceTrackInfo = await findBestSourceTrack(targetLanguage);
  if (!sourceTrackInfo) {
    throw new Error("No subtitle track with cues was found for this video.");
  }

  const sourceTrack = sourceTrackInfo.element;
  const sourceTextTrack = sourceTrackInfo.textTrack;
  const sourceLanguage = sourceTrackInfo.language || "auto";
  const sourceBase = getLanguageBase(sourceLanguage);
  const targetBase = getLanguageBase(targetLanguage);

  if (sourceBase && targetBase && sourceBase === targetBase) {
    throw new Error("Source and target languages are the same. Choose a different target language.");
  }

  sourceTextTrack.mode = "showing";
  const cues = await loadTrackCues(sourceTextTrack, true);
  if (!cues.length) {
    throw new Error("Subtitle cue list is empty.");
  }

  const videoKey = buildVideoKey(sourceTrack, cues);
  if (translatedVideoKey && translatedVideoKey === videoKey) {
    throw new Error("Translation has already been applied for this video.");
  }

  if (translationInProgress) {
    throw new Error("Translation is already in progress.");
  }

  translationInProgress = true;

  try {
    const groups = buildSentenceGroups(cues);
    const segments = groups.map((group) => group.text);

    const response = await requestTranslations({
      segments,
      sourceLanguage,
      targetLanguage
    });

    const translations = response.translations;
    for (let i = 0; i < groups.length; i++) {
      const group = groups[i];
      const translatedText = translations[i] && translations[i].trim() ? translations[i] : group.text;
      const formatted = formatCueText(translatedText);

      for (let cueIndex = group.start; cueIndex <= group.end; cueIndex++) {
        cues[cueIndex].text = formatted;
      }
    }

    translatedVideoKey = videoKey;

    return {
      translatedCount: cues.length,
      groupCount: groups.length,
      mode: response.mode || "single",
      sourceLanguage
    };
  } finally {
    translationInProgress = false;
  }
}

function getSubtitleTracks() {
  const tracks = Array.from(document.getElementsByTagName("track"));
  return tracks
    .map((element, index) => {
      const textTrack = element.track;
      const kind = String(element.kind || (textTrack && textTrack.kind) || "").toLowerCase();
      if (!textTrack) {
        return null;
      }
      if (kind && kind !== "subtitles" && kind !== "captions") {
        return null;
      }

      const language = normalizeLanguageCode(element.srclang || textTrack.language || "");
      const label = normalizeTrackLabel(element.label || textTrack.label || "");
      return {
        index,
        element,
        textTrack,
        language,
        label,
        isShowing: textTrack.mode === "showing",
        isDefault: !!element.default,
        isEnglish: getLanguageBase(language) === "en",
        isAutoGenerated: isAutoGeneratedTrack({ element, language, label })
      };
    })
    .filter(Boolean);
}

async function findBestSourceTrack(targetLanguage) {
  const targetBase = getLanguageBase(targetLanguage);
  const tracks = getSubtitleTracks();
  if (!tracks.length) {
    return null;
  }

  const defaultEnglish = sortTracksByPreference(
    tracks.filter((track) => track.isEnglish && track.isDefault && !track.isAutoGenerated),
    targetBase
  );
  const defaultEnglishMatch = await findFirstTrackWithCues(defaultEnglish);
  if (defaultEnglishMatch) {
    return defaultEnglishMatch;
  }

  const nonAutoAnyLanguage = sortTracksByPreference(
    tracks.filter((track) => !track.isAutoGenerated),
    targetBase
  );
  const nonAutoMatch = await findFirstTrackWithCues(nonAutoAnyLanguage);
  if (nonAutoMatch) {
    return nonAutoMatch;
  }

  const autoEnglish = sortTracksByPreference(
    tracks.filter((track) => track.isEnglish && track.isAutoGenerated),
    targetBase
  );
  const autoEnglishMatch = await findFirstTrackWithCues(autoEnglish);
  if (autoEnglishMatch) {
    return autoEnglishMatch;
  }

  return findFirstTrackWithCues(sortTracksByPreference(tracks, targetBase));
}

async function findFirstTrackWithCues(tracks) {
  for (const track of tracks) {
    const cues = await loadTrackCues(track.textTrack, false);
    if (cues.length) {
      return track;
    }
  }
  return null;
}

async function loadTrackCues(textTrack, persistMode) {
  const originalMode = textTrack.mode;
  if (textTrack.mode === "disabled") {
    textTrack.mode = "hidden";
  }

  let cues = Array.from(textTrack.cues || []);
  for (let i = 0; i < TRACK_CUE_LOAD_ATTEMPTS && !cues.length; i++) {
    await sleep(TRACK_CUE_LOAD_INTERVAL_MS);
    cues = Array.from(textTrack.cues || []);
  }

  if (!persistMode && textTrack.mode !== originalMode) {
    textTrack.mode = originalMode;
  }

  return cues;
}

function scoreTrack(track, targetBase) {
  const trackBase = getLanguageBase(track.language);
  let score = 0;

  if (track.isShowing) {
    score += 100;
  }
  if (track.isDefault) {
    score += 40;
  }
  if (track.language) {
    score += 20;
  }
  if (track.isEnglish) {
    score += 15;
  }
  if (trackBase && targetBase && trackBase !== targetBase) {
    score += 10;
  }
  if (!track.isAutoGenerated) {
    score += 30;
  }

  return score;
}

function sortTracksByPreference(tracks, targetBase) {
  return tracks
    .map((track) => ({
      ...track,
      score: scoreTrack(track, targetBase)
    }))
    .sort((a, b) => b.score - a.score || a.index - b.index);
}

function normalizeLanguageCode(languageCode) {
  return String(languageCode || "")
    .trim()
    .toLowerCase()
    .replace(/_/g, "-");
}

function getLanguageBase(languageCode) {
  const normalized = normalizeLanguageCode(languageCode);
  if (!normalized) {
    return "";
  }
  return normalized.split("-")[0];
}

function normalizeTrackLabel(label) {
  return String(label || "")
    .trim()
    .toLowerCase();
}

function isAutoGeneratedTrack(track) {
  const haystack = [
    track.label,
    track.language,
    track.element && track.element.src ? String(track.element.src).toLowerCase() : ""
  ]
    .filter(Boolean)
    .join(" ");

  if (!haystack) {
    return false;
  }

  if (/auto[\s-]?generated|autogenerated|machine[\s-]?translated|auto[\s-]?translated|speech[\s-]?recognition|\basr\b/.test(haystack)) {
    return true;
  }

  if (/\bauto\b/.test(haystack) && /\b(generate|generated|translate|translated|translation)\b/.test(haystack)) {
    return true;
  }

  return false;
}

function isTranslationAppliedForCurrentVideo() {
  if (!translatedVideoKey) {
    return false;
  }

  const tracks = getSubtitleTracks();
  for (const track of tracks) {
    const cues = Array.from(track.textTrack.cues || []);
    if (!cues.length) {
      continue;
    }

    if (translatedVideoKey === buildVideoKey(track.element, cues)) {
      return true;
    }
  }

  return false;
}

function buildVideoKey(track, cues) {
  const trackSource = track.src || "inline-track";
  const firstCue = cues[0] ? `${cues[0].startTime}-${cues[0].endTime}` : "none";
  const lastCue = cues[cues.length - 1] ? `${cues[cues.length - 1].startTime}-${cues[cues.length - 1].endTime}` : "none";
  return `${location.pathname}|${trackSource}|${cues.length}|${firstCue}|${lastCue}`;
}

function buildSentenceGroups(cues) {
  const normalized = cues.map((cue) => normalizeCueText(cue.text));
  const groups = [];

  let groupStart = 0;
  let groupParts = [];
  let groupChars = 0;

  for (let i = 0; i < normalized.length; i++) {
    const currentText = normalized[i] || "";
    groupParts.push(currentText);
    groupChars += currentText.length + 1;

    const nextText = i + 1 < normalized.length ? normalized[i + 1] : "";
    const isLast = i === normalized.length - 1;
    const sentenceBoundary = isSentenceBoundary(currentText, nextText);
    const groupTooLong = groupChars >= MAX_GROUP_CHARS;

    if (isLast || sentenceBoundary || groupTooLong) {
      const merged = mergeGroupParts(groupParts);
      groups.push({
        start: groupStart,
        end: i,
        text: merged || currentText
      });

      groupStart = i + 1;
      groupParts = [];
      groupChars = 0;
    }
  }

  return groups;
}

function isSentenceBoundary(currentText, nextText) {
  if (!nextText) {
    return true;
  }

  const endsSentence = /[.!?]["')\]]?$/.test(currentText);
  const nextStartsSentence = /^["'([{]?[A-Z0-9]/.test(nextText);

  return endsSentence && nextStartsSentence;
}

function mergeGroupParts(parts) {
  return parts
    .map((part) => part.replace(/\s+/g, " ").trim())
    .filter(Boolean)
    .join(" ")
    .replace(/\s+([,.!?;:])/g, "$1")
    .trim();
}

function requestTranslations(payload) {
  return new Promise((resolve, reject) => {
    chrome.runtime.sendMessage({ type: "translateSubtitles", payload }, (response) => {
      if (chrome.runtime.lastError) {
        reject(new Error("Failed to connect to background script."));
        return;
      }

      if (!response || !response.ok) {
        reject(new Error((response && response.error) || "Translation service request failed."));
        return;
      }

      if (!Array.isArray(response.translations)) {
        reject(new Error("Translation response format is invalid."));
        return;
      }

      resolve(response);
    });
  });
}

function normalizeCueText(text) {
  const decoded = decodeHtml(text || "");
  return decoded.replace(/\s+/g, " ").trim();
}

function decodeHtml(text) {
  const parser = document.createElement("textarea");
  parser.innerHTML = text;
  return parser.value;
}

function formatCueText(text) {
  const clean = (text || "").replace(/\s+/g, " ").trim();
  if (!clean) {
    return "";
  }

  if (clean.length <= MAX_LINE_LENGTH) {
    return clean;
  }

  const midpoint = Math.floor(clean.length / 2);
  const minSplit = Math.max(22, Math.floor(clean.length * 0.35));
  const maxSplit = Math.min(clean.length - 12, Math.floor(clean.length * 0.65));
  let splitIndex = -1;

  for (let offset = 0; offset < clean.length; offset++) {
    const right = midpoint + offset;
    if (right >= minSplit && right <= maxSplit && clean[right] === " ") {
      splitIndex = right;
      break;
    }

    const left = midpoint - offset;
    if (left >= minSplit && left <= maxSplit && clean[left] === " ") {
      splitIndex = left;
      break;
    }
  }

  if (splitIndex === -1) {
    splitIndex = clean.lastIndexOf(" ", MAX_LINE_LENGTH);
  }

  if (splitIndex === -1) {
    splitIndex = clean.indexOf(" ", MAX_LINE_LENGTH);
  }

  if (splitIndex === -1) {
    return clean;
  }

  const firstLine = clean.slice(0, splitIndex).trim();
  const secondLine = clean.slice(splitIndex + 1).trim();
  return `${firstLine}\n${secondLine}`;
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
